markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: python
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

title: Thomas Hudson
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      theme: "#305864"